namespace Sushi.Transpilation.Intrinsics;

public enum IntrinsicId
{
    Print,
    Println,
    StringTrim,
    StringLower,
    StringUpper,
    StringSplit,
    StringContains,
    StringStartsWith,
    StringEndsWith,
    StringReplace,
    StringIsMatch,
    StringMatch,
    IoReadText,
    IoWriteText,
    IoExists,
    PathJoin,
    PathDirname,
    PathBasename,
    EnvGet,
    EnvSet,
    ProcessArgs,
    ProcessExit,
    ProcessRun,
    ProcessPipeline,
    ProcessFail,
    ProcessRequireSuccess,
    OsCwd,
    OsChdir,
    FsGlob,
    HttpGet,
    HttpPost
}
